### ISSUE TITLE
httpsに対応する

### ISSUE THREAD

**Issue by yutashi** [xshellinc/isaac_website#17]

**Comment by miminashi** [comment]
github pagesをやめて、s3にしてもよいかもしれません。
その場合s3へのデプロイを考えておかないとサイトの更新が手間になりますが。
http://matetsu.hatenablog.com/entry/2015/12/05/200425

**Comment by miminashi** [comment]
httpsリバースプロキシとして使うならCloudFrontではなくCloudflareという手もあります。
http://matetsu.hatenablog.com/entry/2015/12/05/200425

**Comment by miminashi** [comment]
cloudfrontでは別途SSL証明書用意しなくても独自ドメインのSSLいけるっぽいですね
https://blog.euonymus.info/cloudflare%E3%81%A7ssl%E3%82%92%E5%B0%8E%E5%85%A5%E3%81%99%E3%82%8B%E6%99%82%E3%81%AE%E6%B3%A8%E6%84%8F/

**Comment by yutashi** [comment]
https://isaacapp.io
できたのでcloseします
